ready for coderewiew
RomanMorf/Front-end_School_HW_1 pull request #1
Opened 2021-12-20 13:51 UTC by RomanMorf

2021-12-20 21:28 UTC, AlisaVlasova requested changes

2021-12-20 21:28 UTC, AlisaVlasova commented on README.md
> +Заменить его на новый список не составит труда, как только API заработает.
Привет)
Ну погнали!

Readme, в целом, гуд  но еще желательно прописать npm команды для установки, запуска проекта и тд

2021-12-20 21:28 UTC, AlisaVlasova commented on src/components/Header.vue
> +    font-weight: 400;
Два раза повторяется "fw: 400"

В целом по стилям, намного удобнее читать и править потом, когда они тоже разбиты отступами на секции (сначала позиционирование, отступ, флексы, отступ, размеры и тд)
Не думаю что есть смысл это поправлять, но на будущее))

2021-12-20 21:28 UTC, AlisaVlasova commented on src/components/SideBar.vue
> +                <h3 @click="$router.push('/profile/' + user.authorMeta.name )">
Метод роутера повторяется здесь и в 23 строке, можно вынести в отдельный метод

2021-12-20 21:28 UTC, AlisaVlasova commented on src/components/Header.vue
> +          <input type="text" class="header_input" placeholder="Поиск аккаунтов и видео">
Когда в теге больше двух атрибутов, лучше форматировать в столбик, так лучше читается
Думаю, что это точно не критично, больше на будущее)
Пишу только здесь, но актуально по всему проекту

2021-12-20 21:28 UTC, AlisaVlasova commented on src/filters/shortNumber.filter.js
> +    return newValue
Перед return отступ (отделяем результат функции)
Ниже тоже актуально

2021-12-20 21:28 UTC, AlisaVlasova commented on src/filters/shortNumber.filter.js
> +  const newValue = null
Здесь лучше обьявить не константу а let, а в условиях уже давать значения
А сейчас получается неиспользуемая переменная, а в условиях каждый раз обьявляется и юзается новая с таким же именем

Между переменной и ифом просится отступ (разбиваем функции на смысловые блоки)

2021-12-20 21:28 UTC, AlisaVlasova commented on src/filters/shortNumber.filter.js
> +    let newValue = number
Вот здесь уже не использовать let для новой переменной, а присваивать number той что во 2 строке
Ниже тоже актуально

2021-12-20 21:28 UTC, AlisaVlasova commented on src/mixins/player.mixins.js
> +    playToggle() {// переключает режим "PLAY" на "PAUSE", и наоборот
Коммент не обязателен, название функции говорит само за себя
Все ниже тоже актуально

2021-12-20 21:28 UTC, AlisaVlasova commented on src/store/player.js
> +    clearPlayerInfo(state, info) {
info в аргументах лишняя, не используется

2021-12-20 21:28 UTC, AlisaVlasova commented on src/store/player.js
> +    GET_PLAYER_INFO({ dispatch, commit, getters }) {
dispatch, getters не используются
Ниже тоже актуально

2021-12-20 21:28 UTC, AlisaVlasova commented on src/store/index.js
> +    slearError (state) {
slear - это clear, если я не ошибаюсь?
И не вижу чтобы эти мутации где-то использовались в коде, кроме user.js 40стр, но там я оставила тоже коммент

2021-12-20 21:28 UTC, AlisaVlasova commented on src/store/user.js
> +        commit('setError', error)
Не уверенна что так можно вызвать мутацию из глобального стейта (setError не в этом модуле) и в других методах используется вывод ошибки в консоль

[Вот про мутации глобального стейта](https://ru.stackoverflow.com/questions/1099177/%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D0%B8-%D0%B2-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F%D1%85-vuex)

2021-12-20 21:28 UTC, AlisaVlasova commented on src/views/Profile.vue
> +          <a :href="INFO.user.bioLink.link">{{ INFO.user.bioLink.link }}</a>
Можно добавить атрибут target="_blank" к ссылке, чтобы открывать на новой вкладке

2021-12-20 21:28 UTC, AlisaVlasova commented on src/views/Profile.vue
> +      userInfo: null,
Не используется

2021-12-20 21:28 UTC, AlisaVlasova commented on src/mixins/player.mixins.js
> +      const volumeValue = this.volume || 30
Отступ после переменной просится

2021-12-20 21:28 UTC, AlisaVlasova commented on src/views/Profile.vue
> +</style>
У меня пока все)
Отличная работа!)

2021-12-30 16:07 UTC, RomanMorf commented on src/views/Profile.vue
> +</style>
Спасибо за ревью )
Сейчас займусь исправлениями )

2021-12-30 18:52 UTC, AlisaVlasova approved these changes

2021-12-30 18:53 UTC, AlisaVlasova commented
Все супер!)

2021-12-31 09:00 UTC, atna reviewed
@RomanMorf привіт)
@AlisaVlasova провела чудове ревʼю і описала багато важливих моментів по коду.
Постараюсь зі своєї сторони також додати корисні рекомендації)

2021-12-31 10:47 UTC, atna reviewed
@RomanMorf привіт)
@AlisaVlasova провела чудове ревʼю і описала багато важливих моментів по коду.
Постараюсь зі своєї сторони також додати корисні рекомендації)

2021-12-31 10:47 UTC, atna commented on src/assets/profile_name-title.svg
> +<svg v-if="INFO.user.verified" class="verified jsx-4013687392" width="28" height="28" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="24" cy="24" r="24" fill="#20D5EC">
Перевірки і класи краще виносити на рівень вище. В цьому файлі вони не дуже помітні і іх легко затерти при оновленні файлу

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +  <div class="card" :id="'card-' + item.id">
`'card-' + item.id ` - краще винести в computed властивість, щоб не повторюватись при селекті елемента. Також для доступу до елемента шаблона можна використати ref [https://ru.vuejs.org/v2/api/#ref](https://ru.vuejs.org/v2/api/#ref)

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +          <img class="verified jsx-4013687392" src="@/assets/card_verified.svg" alt="verified">
`jsx-4013687392` - здається це клас, який не використовуються, можна його прибрати

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +          <span v-if="item.musicMeta.musicName === 'original sound'" class="card_meta-audio-name">оригинальная песня</span>
'original sound' - схоже це якесь статичне значення з api, такі речі краще виносити в константи

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +      if (startStopLine < elemTop && startStopLine < elemTop + elemHeigth) {
Можу помилятися, але здається `startStopLine < elemTop` тут не потрібна, ця перевірка буде завжди правдива, якщо `startStopLine < elemTop + elemHeigth` правдива

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +        this.isPlay ? this.playerStop() : null;
перевірку `this.isPlay` можна занести в сам метод playerStop

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +      }
здається всю цю умово можна скоротити до такої
```js
if (startStopLine > elemTop && startStopLine < elemTop + elemHeigth) {
  this.playerPlay();
} else {
  this.playerStop();
}
```

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +      -ms-transform: scaleY(0.5);
префікси можна не додавати, їх добавить autoprefixer
нижче по коду також їх можна прибрати

2021-12-31 10:47 UTC, atna commented on src/components/Card.vue
> +            <img v-if="!MUTED" src="@/assets/card_player_muted-off.svg" alt="muted off">
тут зрозуміліше буде використати v-else замість v-if="!MUTED"

2021-12-31 10:47 UTC, atna commented on src/components/SideBar.vue
> +    }
бажано було би використовувати один стиль форматування - або з пустою лінією між правилами елементів, або без

2021-12-31 10:47 UTC, atna commented on src/components/SmallVideo.vue
> +  props: ["video"],
для пропсів гарною практикою є валідація вхідних даних [https://ru.vuejs.org/v2/guide/components-props.html#%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2](https://ru.vuejs.org/v2/guide/components-props.html#%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2)

2021-12-31 10:47 UTC, atna commented on src/mixins/player.mixins.js
> +    checkParams() {
судячи з того що робить функція, її доречніше було б назвати resetParams

2021-12-31 10:47 UTC, atna commented on src/store/player.js
> +    MUTED: (s) => s.playerInfo.muted,
можливо, це дискусійний момент, але функція гетерів - запобігання дуювлювання коду обчислень в різних компонетах і кешування іх резальтутів
оскільки тут ніяких обчислень не відбувається, використовувати гетери особливо не має сенсу, можна напряму брати дані зі стейту

2021-12-31 10:47 UTC, atna commented on src/store/user.js
> +          "x-rapidapi-key": "c1257dc04cmshd888bbb072eb770p1f2b8ajsnbf16d4cd1d66",
дані хоста, ключа доступу, базового урла і т.д. краще виносити в константи в окремому файлі і підключати їх, там де потрібно
таким чином, у випаду змін, ми зможем редагувати їх в одному місці

2021-12-31 10:47 UTC, atna commented on src/views/Profile.vue
> +              :src="INFO.user.avatarMedium || INFO.user.avatarLarger || INFO.user.avatarThumb"
`INFO.user.avatarMedium || INFO.user.avatarLarger || INFO.user.avatarThumb` - можна винести в computed і не дублювати в шаблоні

2021-12-31 10:47 UTC, atna commented on src/views/Profile.vue
> +  components: {
зазвичай ресурси компонента добавляються перед іншими опціями [https://ru.vuejs.org/v2/style-guide/#%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D0%BF%D1%86%D0%B8%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%B0-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F](https://ru.vuejs.org/v2/style-guide/#%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D0%BF%D1%86%D0%B8%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%B0-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F)

2021-12-31 17:53 UTC, RomanMorf commented on src/components/Card.vue
> +          <span v-if="item.musicMeta.musicName === 'original sound'" class="card_meta-audio-name">оригинальная песня</span>
Мне кажется, что это показывает, что песня оригинальная и не кем не переделана.

2021-12-31 17:55 UTC, RomanMorf commented on src/components/Card.vue
> +            <img v-if="!MUTED" src="@/assets/card_player_muted-off.svg" alt="muted off">
Согласен )

2021-12-31 18:36 UTC, RomanMorf commented on src/store/user.js
> +          "x-rapidapi-key": "c1257dc04cmshd888bbb072eb770p1f2b8ajsnbf16d4cd1d66",
Вынес в отдельный файл и импортировал в места, где они были необходимы.

2022-01-01 13:26 UTC, atna approved these changes

2022-02-06 20:39 UTC, merged